spring:
  application:
    name: spring-boot-grpc-eureka
eureka:
  server:
    use-read-only-response-cache: false
    eviction-interval-timer-in-ms: 3000
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/,http://127.0.0.1:9001/eureka/
